[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
optimizer_runs = 190
solc = "0.8.27"
gas_reports = ["*"]
fs_permissions = [
    { access = "read", path = "./"},
    { access = "read-write", path = "./deployment-scripts/"}
]
via_ir = false
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.lint]
severity = ["high", "med"]  
lint_on_build = true

[profile.test]
no_match_test = "(invariant_)"
no_match_contract = "(Invariants)"
gas_reports = ["*"]

[profile.invariant]
runs = 256
depth = 500
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
match_test = "invariant_"
show_solidity = true

[profile.coverage]
via_ir = true
no_match_test = "(invariant_)"
no_match_contract = "(Script)"
no_match_coverage= "(script|test|fuzz|e2e)"

[profile.coverage.optimizer_details]
constantOptimizer = true
yul = true

[profile.coverage.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ''

[profile.script]
verbosity = 2
ignore_warnings = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options